config/routes.rb
# Routes
Rails.application.routes.draw do

  # Devise
  devise_for :employees, controllers: { registrations: 'registrations' }

  # Resources
  resources :customer_statuses
  resources :employees
  resources :orders do collection { post :import } end
  resources :customers do collection { post :import } end
  resources :vendors do collection { post :import } end
  resources :employee_statuses
  resources :shippers
  resources :payment_types
  resources :countries do collection { post :import } end
  resources :order_statuses
  resources :vendor_statuses
  resources :states do collection { post :import } end
  resources :order_lines do collection { post :import } end
  resources :products do collection { post :import } end

  # Namespaces
  namespace :admin do
    resources :employees, only: :show do
      post :generate_new_password_email
    end
  end

  # Root
  root 'pages#index'

  # Destroy Employee
  match '/pages/employee/:id', to: 'pages#toggle_employee',
                               as: 'toggle_employee',
                               via: 'put'

  # Toggle Admin
  match '/pages/employee/admin/:id', to: 'pages#toggle_admin',
                                     as: 'toggle_admin',
                                     via: 'put'

  # Destroy Customer
  match '/pages/customer/:id', to: 'pages#toggle_customer',
                               as: 'toggle_customer',
                               via: 'put'

  # Destroy Vendor
  match '/pages/vendor/:id', to: 'pages#toggle_vendor',
                             as: 'toggle_vendor',
                             via: 'put'

  # Destroy Order
  match '/pages/order/:id', to: 'pages#toggle_order',
                            as: 'toggle_order',
                            via: 'put'

  # Toggle Order Status
  match '/pages/order/status/:id', to: 'pages#toggle_order_status',
                                   as: 'toggle_order_status',
                                   via: 'put'

  # Toggle Product Status
  match '/pages/order/product/status/:id', to: 'pages#toggle_product_status',
                                           as: 'toggle_product_status',
                                           via: 'put'

  # Update Order
  match '/pages/customer/update/:id', to: 'pages#update_customer',
                                      as: 'update_customer',
                                      via: 'patch'

  # Pages
  get 'pages/dashboard', to: 'pages#dashboard', as: 'dashboard'

  get 'pages/usermgmt', to: 'pages#usermgmt', as: 'usermgmt'

  get 'pages/customermgmt', to: 'pages#customermgmt', as: 'customermgmt'

  get 'pages/vendormgmt', to: 'pages#vendormgmt', as: 'vendormgmt'

  get 'pages/shippingmgmt', to: 'pages#shippingmgmt', as: 'shippingmgmt'

  get 'pages/ordermgmt', to: 'pages#ordermgmt', as: 'ordermgmt'

  get 'pages/reports_customers', to: 'pages#reports_customers', as: 'reports_customers'

  get 'pages/reports_employees', to: 'pages#reports_employees', as: 'reports_employees'

  get 'pages/reports_orders', to: 'pages#reports_orders', as: 'reports_orders'

  get 'pages/reports_products', to: 'pages#reports_products', as: 'reports_products'

  get 'pages/reports_statuses', to: 'pages#reports_statuses', as: 'reports_statuses'

  get 'pages/reports_vendors', to: 'pages#reports_vendors', as: 'reports_vendors'

  get 'pages/importmgmt', to: 'pages#importmgmt', as: 'importmgmt'

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/views/unused/order_statuses.unused/_form.html.erb
<%= form_with(model: order_status, local: true) do |form| %>
  <% if order_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_status.errors.count, "error") %> prohibited this order_status from being saved:</h2>

      <ul>
      <% order_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_status_description %>
    <%= form.text_field :order_status_description, id: :order_status_order_status_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unused/order_statuses.unused/edit.html.erb
<h1>Editing Order Status</h1>

<%= render 'form', order_status: @order_status %>

<%= link_to 'Show', @order_status %> |
<%= link_to 'Back', order_statuses_path %>

app/views/unused/order_statuses.unused/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Order status description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_statuses.each do |order_status| %>
      <tr>
        <td><%= order_status.order_status_description %></td>
        <td><%= link_to 'Show', order_status %></td>
        <td><%= link_to 'Edit', edit_order_status_path(order_status) %></td>
        <td><%= link_to 'Destroy', order_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Status', new_order_status_path %>

app/views/unused/order_statuses.unused/new.html.erb
<h1>New Order Status</h1>

<%= render 'form', order_status: @order_status %>

<%= link_to 'Back', order_statuses_path %>

app/views/unused/order_statuses.unused/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order status description:</strong>
  <%= @order_status.order_status_description %>
</p>

<%= link_to 'Edit', edit_order_status_path(@order_status) %> |
<%= link_to 'Back', order_statuses_path %>