config/routes.rb
# Routes
Rails.application.routes.draw do

  # Devise
  devise_for :employees, controllers: { registrations: 'registrations' }

  # Resources
  resources :customer_statuses
  resources :employees
  resources :orders do collection { post :import } end
  resources :customers do collection { post :import } end
  resources :vendors do collection { post :import } end
  resources :employee_statuses
  resources :shippers
  resources :payment_types
  resources :countries do collection { post :import } end
  resources :order_statuses
  resources :vendor_statuses
  resources :states do collection { post :import } end
  resources :order_lines do collection { post :import } end
  resources :products do collection { post :import } end

  # Namespaces
  namespace :admin do
    resources :employees, only: :show do
      post :generate_new_password_email
    end
  end

  # Root
  root 'pages#index'

  # Destroy Employee
  match '/pages/employee/:id', to: 'pages#toggle_employee',
                               as: 'toggle_employee',
                               via: 'put'

  # Toggle Admin
  match '/pages/employee/admin/:id', to: 'pages#toggle_admin',
                                     as: 'toggle_admin',
                                     via: 'put'

  # Destroy Customer
  match '/pages/customer/:id', to: 'pages#toggle_customer',
                               as: 'toggle_customer',
                               via: 'put'

  # Destroy Vendor
  match '/pages/vendor/:id', to: 'pages#toggle_vendor',
                             as: 'toggle_vendor',
                             via: 'put'

  # Destroy Order
  match '/pages/order/:id', to: 'pages#toggle_order',
                            as: 'toggle_order',
                            via: 'put'

  # Toggle Order Status
  match '/pages/order/status/:id', to: 'pages#toggle_order_status',
                                   as: 'toggle_order_status',
                                   via: 'put'

  # Toggle Product Status
  match '/pages/order/product/status/:id', to: 'pages#toggle_product_status',
                                           as: 'toggle_product_status',
                                           via: 'put'

  # Update Order
  match '/pages/customer/update/:id', to: 'pages#update_customer',
                                      as: 'update_customer',
                                      via: 'patch'

  # Pages
  get 'pages/dashboard', to: 'pages#dashboard', as: 'dashboard'

  get 'pages/usermgmt', to: 'pages#usermgmt', as: 'usermgmt'

  get 'pages/customermgmt', to: 'pages#customermgmt', as: 'customermgmt'

  get 'pages/vendormgmt', to: 'pages#vendormgmt', as: 'vendormgmt'

  get 'pages/shippingmgmt', to: 'pages#shippingmgmt', as: 'shippingmgmt'

  get 'pages/ordermgmt', to: 'pages#ordermgmt', as: 'ordermgmt'

  get 'pages/reports_customers', to: 'pages#reports_customers', as: 'reports_customers'

  get 'pages/reports_employees', to: 'pages#reports_employees', as: 'reports_employees'

  get 'pages/reports_orders', to: 'pages#reports_orders', as: 'reports_orders'

  get 'pages/reports_products', to: 'pages#reports_products', as: 'reports_products'

  get 'pages/reports_statuses', to: 'pages#reports_statuses', as: 'reports_statuses'

  get 'pages/reports_vendors', to: 'pages#reports_vendors', as: 'reports_vendors'

  get 'pages/importmgmt', to: 'pages#importmgmt', as: 'importmgmt'

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_breadcrumbs.html.erb
<!-- Breadcrumb list -->
<ol class="breadcrumb">

    <!-- Show breadcrumbs -->
    <%= render_breadcrumbs :tag => :li %>
</ol>

app/views/partials/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer">

  <!-- Container -->
  <div class="container">

    <!-- Footer Content -->
    <div class="text-center">
      <small>Copyright © Anchor 8 Solutions 2018</small>
      <%= image_tag("anchor8.png", width: '45px') %>
    </div>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

  <!-- Title Button (Top) -->
  <%= link_to image_tag("appLOGO.png", width: '60px'), dashboard_url, class: "nav-link" %>

  <!-- Logged in -->
  <div class="offset-md-2 navbar-nav">
    <%= link_to("Currently logged in as: " + current_employee.email, usermgmt_url, class: "nav-link  nav-item ") %>
  </div>

  <!-- Nav -->
  <div class="collapse navbar-collapse" id="navbarResponsive">

    <!-- Side Nav -->
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

      <!-- Dashbaord Nav Button -->
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">

        <%= link_to(dashboard_url, class: "nav-link") do %>
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">
                Dashboard
          </span>
        <% end %>
      </li>

      <!-- Reports Nav Button -->
      <li class="nav-item dropdown" data-toggle="tooltip" data-placement="right" title="Reports">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bar-chart"></i>
          <span class="nav-link-text">
                Reports
          </span>
        </a>

          <div class="dropdown-menu ml-5" aria-labelledby="navbarDropdown">

            <%= link_to(reports_orders_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Orders
              </span>
            <% end %>

            <%= link_to(reports_products_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Products
              </span>
            <% end %>

            <%= link_to(reports_customers_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Customers
              </span>
            <% end %>

            <%= link_to(reports_vendors_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Vendors
              </span>
            <% end %>

            <%= link_to(reports_statuses_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Statuses
              </span>
            <% end %>

            <%= link_to(reports_employees_url, class: "dropdown-item") do %>
              <i class="fa fa-bar-chart"></i>
              <span class="">
                    Employees
              </span>
            <% end %>

          </div>

      </li>

      <!-- Customer Management Nav Button -->
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Customer Management">

        <%= link_to(customermgmt_url, class: "nav-link") do %>
          <i class="fa fa-group"></i>
          <span class="nav-link-text">
                Customer Management
          </span>
        <% end %>
      </li>

      <!-- Order Management Nav Button -->
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Order Management">

        <%= link_to(ordermgmt_url, class: "nav-link") do %>
          <i class="fa fa-file-text-o"></i>
          <span class="nav-link-text">
                Order Management
          </span>
        <% end %>
      </li>

      <!-- Shipping Management Nav Button -->
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Shipping Management">

        <%= link_to(shippingmgmt_url, class: "nav-link") do %>
          <i class="fa fa-plane"></i>
          <span class="nav-link-text">
                Shipping Management
          </span>
        <% end %>
      </li>

      <!-- Vendor Management Nav Button -->
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Vendor Management">

        <%= link_to(vendormgmt_url, class: "nav-link") do %>
          <i class="fa fa-handshake-o"></i>
          <span class="nav-link-text">
                Vendor Management
          </span>
        <% end %>
      </li>

      <!-- Import Management Nav Button -->
      <% if current_employee.admin? %>
        <!-- Admin true -->
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Import Management">

          <%= link_to(importmgmt_url, class: "nav-link") do %>
            <i class="fa fa-fw fa-upload"></i>
            <span class="nav-link-text">Import Management</span>
          <% end %>

        </li>
      <% end %>

    </ul>

    <!-- Collapse Nav Bar Button (At bottom) -->
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>

    <!-- Top Nav -->
    <ul class="navbar-nav ml-auto">

      <!-- User Management -->
      <li class="nav-item" title="User Management">

        <%= link_to("User Management", usermgmt_url, class: "nav-link") %>
      </li>

      <!-- Logout -->
      <li class="nav-item">

        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>
          Logout
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_scroll-to-top.html.erb
<!-- Scroll to top button -->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fa fa-angle-up"></i>
</a>