config/routes.rb
# Routes
Rails.application.routes.draw do

  # Devise
  devise_for :employees, controllers: { registrations: 'registrations' }

  # Resources
  resources :customer_statuses
  resources :employees
  resources :orders do collection { post :import } end
  resources :customers do collection { post :import } end
  resources :vendors do collection { post :import } end
  resources :employee_statuses
  resources :shippers
  resources :payment_types
  resources :countries do collection { post :import } end
  resources :order_statuses
  resources :vendor_statuses
  resources :states do collection { post :import } end
  resources :order_lines do collection { post :import } end
  resources :products do collection { post :import } end

  # Namespaces
  namespace :admin do
    resources :employees, only: :show do
      post :generate_new_password_email
    end
  end

  # Root
  root 'pages#index'

  # Destroy Employee
  match '/pages/employee/:id', to: 'pages#toggle_employee',
                               as: 'toggle_employee',
                               via: 'put'

  # Toggle Admin
  match '/pages/employee/admin/:id', to: 'pages#toggle_admin',
                                     as: 'toggle_admin',
                                     via: 'put'

  # Destroy Customer
  match '/pages/customer/:id', to: 'pages#toggle_customer',
                               as: 'toggle_customer',
                               via: 'put'

  # Destroy Vendor
  match '/pages/vendor/:id', to: 'pages#toggle_vendor',
                             as: 'toggle_vendor',
                             via: 'put'

  # Destroy Order
  match '/pages/order/:id', to: 'pages#toggle_order',
                            as: 'toggle_order',
                            via: 'put'

  # Toggle Order Status
  match '/pages/order/status/:id', to: 'pages#toggle_order_status',
                                   as: 'toggle_order_status',
                                   via: 'put'

  # Toggle Product Status
  match '/pages/order/product/status/:id', to: 'pages#toggle_product_status',
                                           as: 'toggle_product_status',
                                           via: 'put'

  # Update Order
  match '/pages/customer/update/:id', to: 'pages#update_customer',
                                      as: 'update_customer',
                                      via: 'patch'

  # Pages
  get 'pages/dashboard', to: 'pages#dashboard', as: 'dashboard'

  get 'pages/usermgmt', to: 'pages#usermgmt', as: 'usermgmt'

  get 'pages/customermgmt', to: 'pages#customermgmt', as: 'customermgmt'

  get 'pages/vendormgmt', to: 'pages#vendormgmt', as: 'vendormgmt'

  get 'pages/shippingmgmt', to: 'pages#shippingmgmt', as: 'shippingmgmt'

  get 'pages/ordermgmt', to: 'pages#ordermgmt', as: 'ordermgmt'

  get 'pages/reports_customers', to: 'pages#reports_customers', as: 'reports_customers'

  get 'pages/reports_employees', to: 'pages#reports_employees', as: 'reports_employees'

  get 'pages/reports_orders', to: 'pages#reports_orders', as: 'reports_orders'

  get 'pages/reports_products', to: 'pages#reports_products', as: 'reports_products'

  get 'pages/reports_statuses', to: 'pages#reports_statuses', as: 'reports_statuses'

  get 'pages/reports_vendors', to: 'pages#reports_vendors', as: 'reports_vendors'

  get 'pages/importmgmt', to: 'pages#importmgmt', as: 'importmgmt'

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/models/vendor.rb
# Vendor Model
class Vendor < ApplicationRecord
  # Relationships
  belongs_to :state
  belongs_to :vendor_status
  has_many :orders

  # Validations
  validates :contact_name, allow_blank: false, presence: true, format: { with: /\A^\s*[a-zA-Z,\s]+\s*$\z/, message: "Only letters, commas, or spaces for contact name allowed"}
  validates :job_title, allow_blank: false, presence: true, format: { with: /\A^\s*[a-zA-Z,\s]+\s*$\z/, message: "Only letters, commas, or spaces for job title allowed"}
  validates :work_phone, allow_blank: false, presence: true, format: { with: /\A^(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[-]?\d{3}[-]?\d{4}$\z/, message: "Format ( +1-123-123-1234 )"}
  validates :mobile, allow_blank: true, presence: false, format: { with: /\A^(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[-]?\d{3}[-]?\d{4}$\z/, message: "Format ( +1-123-123-1234 )"}
  validates :fax, allow_blank: true, presence: false, format: { with: /\A^(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[-]?\d{3}[-]?\d{4}$\z/, message: "Format ( +1-123-123-1234 )" }
  validates :vendor_email, allow_blank: true, presence: false, format: Devise.email_regexp
  validates :vendor_cc_email, allow_blank: true, presence: false, format: Devise.email_regexp
  validates :website, allow_blank: true, presence: false, format: { with: /\A([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i, message: "Format ( www.website.com ) or ( website.com )" }
  validates :street_address_1, allow_blank: false, presence: true
  validates :street_address_2, allow_blank: true, presence: false
  validates :city, allow_blank: false, presence: true, format: { with: /\A^\s*[a-zA-Z,\s]+\s*$\z/, message: "Only letters, commas, or spaces for city allowed"}
  validates :zip_code, allow_blank: false, presence: true, format: { with: /\A^\d{5}(?:[-\s]\d{4})?$\z/, message: "Format ( 12345 ) or ( 12345-4321 )"}
  validates :deleted_at, allow_blank: true, presence: false

  # Toggle vendor
  def toggle_vendor
    if !deleted_at
      # Deleted at doesn't exist
      update_attribute(:deleted_at, Time.current)
      update_attribute(:vendor_status_id, 4)
    else
      # Deleted at exists
      update_attribute(:deleted_at, nil)
      update_attribute(:vendor_status_id, 3)
    end
  end

  # Import vendors
  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: [:downcase, :symbol]) do |row|
      if [:vendor_email].all? { |header| row.headers.include? header }
        Vendor.create! row.to_hash
      else
        raise "Wrong file."
      end
    end
  end
end

app/controllers/vendors_controller.rb
# Vendors Controller
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    add_breadcrumb 'Vendor Management', vendormgmt_path
    add_breadcrumb 'Create New Vendor'

    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
    add_breadcrumb 'Vendor Management', vendormgmt_path
    add_breadcrumb 'Edit Vendor'
  end

  # POST /vendors
  # POST /vendors.json
  def create
    add_breadcrumb 'Vendor Management', vendormgmt_path
    add_breadcrumb 'Create New Vendor'

    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendormgmt_url, notice: "Vendor was successfully added." }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendormgmt_url, notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendormgmt_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Import vendor data
  def import
    if params[:file].nil?
      # File doesn't exist
      redirect_to importmgmt_url, notice: 'Vendor data file is missing, please choose a csv file.'
    else
      # File exists
      Vendor.import(params[:file])
      redirect_to importmgmt_url, notice: 'Vendor data imported!'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vendor
    @vendor = Vendor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vendor_params
    params.require(:vendor).permit(:state_id, :vendor_status_id, :vendor_name, :contact_name, :job_title, :work_phone, :mobile, :fax, :vendor_email, :vendor_cc_email, :website, :street_address_1, :street_address_2, :city, :zip_code)
  end
end

app/helpers/vendors_helper.rb
# Vendors Helper
module VendorsHelper
end

app/views/vendors/_form.html.erb
<!-- Vendor form card -->
<div class="card">

  <!-- Vendor form card header -->
  <div class="card-header">
  </div>

  <!-- Vendor form card content -->
  <div class="card-body">

    <!-- Vendor form row -->
    <div class="row">

      <!-- Vendor form centered -->
      <div class="mx-auto">

        <!-- Vendor form -->
        <%= form_with(model: vendor, local: true) do |form| %>

          <!-- Error Banner -->
          <% if vendor.errors.any? %>
            <div class="h5 strong text-center mark">
              <% vendor.errors.full_messages.each do |message| %>
                * <%= message %> *
                <br />
              <% end %>
            </div>
          <% end %>

          <!-- Required Mark -->
          <div class="mb-3">
            <font color="red">*</font> = Required
          </div>

          <!-- Row -->
          <div class="row form-group">

            <!-- Vendor Info -->
            <div class="col-md-auto">
              <fieldset><legend>Vendor Info</legend>
              <!-- Vendor name -->
              <div class="field col-md-12">
                <b><%= form.label :vendor_name %></b> <font color="red">*</font><br />
                <%= form.text_field :vendor_name, :size => '20', placeholder: 'Vendor Name', id: :vendor_vendor_name, class: 'form-control' %>
              </div>

              <!-- Contact name -->
              <div class="field mt-1 col-md-12">
                <b><%= form.label :contact_name %></b> <font color="red">*</font><br />
                <%= form.text_field :contact_name, :size => '20', placeholder: 'John Smith', id: :vendor_contact_name, class: 'form-control' %>
              </div>

              <!-- Job title -->
              <div class="field mt-1 col-md-12">
                <b><%= form.label :job_title %></b> <font color="red">*</font><br />
                <%= form.text_field :job_title, :size => '20', placeholder: 'Products Manager', id: :vendor_job_title, class: 'form-control' %>
              </div>

              <!-- Website -->
              <div class="field mt-1 col-md-12">
                <b><%= form.label :website %></b><br />
                <%= form.text_field :website, :size => '25', placeholder: 'www.website.com', id: :vendor_website, class: 'form-control' %>
              </div>

              <!-- Vendor status -->
              <div class="field mt-2 col-md-8">
                <b><%= form.label :vendor_status_id %></b> <font color="red">*</font><br />
                <%= form.collection_select(:vendor_status_id, VendorStatus.all, :id, :vendor_status_type, {prompt: true}, {class: 'form-control'}) %>
              </div>
              </fieldset>
            </div>


            <!-- Vendor Contact -->
            <div class="col-md-auto">
              <fieldset><legend>Vendor Contact</legend>

              <div class="field mt-auto col-md-12">
                <b><%= form.label :vendor_email %></b> <font color="red">*</font><br />
                <%= form.text_field :vendor_email, type: 'email', :size => '25', placeholder: 'email@provider.com', id: :vendor_vendor_email, class: 'form-control' %>
              </div>

              <!-- Vendor cc email -->
              <div class="field mt-1 col-md-12">
                <b><%= form.label :vendor_cc_email %></b><br />
                <%= form.text_field :vendor_cc_email, type: 'email', :size => '25', placeholder: 'email@provider.com', id: :vendor_vendor_cc_email, class: 'form-control' %>
              </div>

              <!-- Work phone -->
              <div class="field mt-1 col-md-8">
                <b><%= form.label :work_phone %></b> <font color="red">*</font><br />
                <%= form.text_field :work_phone, type: 'tel', :size => '15', placeholder: '+1-123-123-1234', id: :vendor_work_phone, class: 'form-control' %>
              </div>

              <!-- Mobile -->
              <div class="field mt-1 col-md-8">
                <b><%= form.label :mobile %></b><br />
                <%= form.text_field :mobile, type: 'tel', :size => '15', placeholder: '+1-123-123-1234', id: :vendor_mobile, class: 'form-control' %>
              </div>

              <!-- Fax -->
              <div class="field mt-1 col-md-8">
                <b><%= form.label :fax %></b><br />
                <%= form.text_field :fax, type: 'tel', :size => '15', placeholder: '+1-123-123-1234', id: :vendor_fax, class: 'form-control' %>
              </div>
              </fieldset>
            </div>

            <!--  Vendor Address -->
            <div class="col-md-auto">
              <fieldset><legend>Vendor Address</legend>
              <!-- Street Address 1 -->
              <div class="field col-md-12">
                <b><%= form.label :street_address_1 %></b> <font color="red">*</font><br />
                <%= form.text_field :street_address_1, :size => '30', placeholder: '123 Street Address', id: :vendor_street_address_1, class: 'form-control' %>
              </div>

              <!-- Street Address 2 -->
              <div class="field mt-1 col-md-12">
                <b><%= form.label :street_address_2 %></b><br />
                <%= form.text_field :street_address_2, :size => '30', placeholder: 'Bldg. 123', id: :vendor_street_address_2, class: 'form-control' %>
              </div>

              <!-- State -->
              <div class="field mt-1 col-md-8">
                <b><%= form.label :state_id %></b> <font color="red">*</font><br />
                <%= form.collection_select(:state_id, State.order(:state_name), :id, :state_name, {prompt: true}, {class: 'form-control'}) %>
              </div>

              <!-- City -->
              <div class="field mt-1 col-md-6">
                <b><%= form.label :city %></b> <font color="red">*</font><br />
                <%= form.text_field :city, :size => '20', placeholder: 'Houston', id: :vendor_city, class: 'form-control' %>
              </div>

              <!-- Zip code -->
              <div class="field mt-1 col-md-5">
                <b><%= form.label :zip_code %></b> <font color="red">*</font><br />
                <%= form.text_field :zip_code, :size => '10', placeholder: '77777-8888', id: :vendor_zip_code, class: 'form-control' %>
              </div>
              </fieldset>
            </div>
          </div>

          <!-- Submit -->
          <div class="actions">
            <%= form.submit :class => 'btn btn-primary btn-sm btn-block mt-4' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Vendor card footer -->
  <div class="card-footer">

  </div>
</div>

app/views/vendors/edit.html.erb
<!-- Page content -->
<% content_for :title, "Edit Vendor" %>

<!-- Content wrapper -->
<div class="content-wrapper">

  <!-- Container (fluid) -->
  <div class="container-fluid">

    <!-- Bread Crumbs -->
    <%= render partial: 'partials/breadcrumbs' %>

    <!-- Vendor form -->
    <%= render 'form', vendor: @vendor %>
  </div>
</div>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Vendor status</th>
      <th>Vendor name</th>
      <th>Contact name</th>
      <th>Job title</th>
      <th>Work phone</th>
      <th>Mobile</th>
      <th>Fax</th>
      <th>Vendor email</th>
      <th>Vendor cc email</th>
      <th>Website</th>
      <th>Street address 1</th>
      <th>Street address 2</th>
      <th>City</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.state %></td>
        <td><%= vendor.vendor_status %></td>
        <td><%= vendor.vendor_name %></td>
        <td><%= vendor.contact_name %></td>
        <td><%= vendor.job_title %></td>
        <td><%= vendor.work_phone %></td>
        <td><%= vendor.mobile %></td>
        <td><%= vendor.fax %></td>
        <td><%= vendor.vendor_email %></td>
        <td><%= vendor.vendor_cc_email %></td>
        <td><%= vendor.website %></td>
        <td><%= vendor.street_address_1 %></td>
        <td><%= vendor.street_address_2 %></td>
        <td><%= vendor.city %></td>
        <td><%= vendor.zip_code %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<% content_for :title, "Create New Vendor" %>

<div class="content-wrapper">

  <div class="container-fluid">

    <!-- Bread Crumbs -->
    <%= render partial: 'partials/breadcrumbs' %>

    <!-- Vendor form -->
    <%= render 'form', vendor: @vendor %>
  </div>
</div>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @vendor.state %>
</p>

<p>
  <strong>Vendor status:</strong>
  <%= @vendor.vendor_status %>
</p>

<p>
  <strong>Vendor name:</strong>
  <%= @vendor.vendor_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @vendor.contact_name %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @vendor.job_title %>
</p>

<p>
  <strong>Work phone:</strong>
  <%= @vendor.work_phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @vendor.mobile %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @vendor.fax %>
</p>

<p>
  <strong>Vendor email:</strong>
  <%= @vendor.vendor_email %>
</p>

<p>
  <strong>Vendor cc email:</strong>
  <%= @vendor.vendor_cc_email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @vendor.website %>
</p>

<p>
  <strong>Street address 1:</strong>
  <%= @vendor.street_address_1 %>
</p>

<p>
  <strong>Street address 2:</strong>
  <%= @vendor.street_address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @vendor.city %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @vendor.zip_code %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>